name: Release

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (or your relevant environment)
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Specify your Node.js version here

    - name: Install dependencies
      run: npm install

    - name: Run build (optional)
      run: npm run build  # Replace with your build command if needed

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}  # Creates a version like v1, v2, v3, etc.
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
        body: |
          Automated release created by GitHub Actions.
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}

    - name: Upload Release Assets (optional)
      if: always()  # Run this step even if previous steps fail
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./path-to-your-artifact  # Replace with the path to your build artifact
        asset_name: artifact-name.zip  # Replace with the name of your artifact
        asset_content_type: application/zip  # Replace with the appropriate content type
